apiVersion: v1
kind: Deployment
metadata:
  name: client-deployment
  selector:
    label:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: rajaraghav/multicontainerclient
